enabled: true            # master toggle
type: "pg"               # only "pg" supported
pg:
  lr: 0.001
  hidden: 32
  eps:
    mom: 0.05
    news: 0.05
    social: 0.05
  lambda:
    lip: 1.0
    gen: 0.0001
  entropy_coef: 0.001
  device: "auto"         # auto | cpu | cuda