# Global settings
seed: 42                     # RNG seed for reproducibility
episodes: 1                  # number of episodes to run

# Universe / data
assets: ["AAPL", "MSFT"]     # symbols must match CSV filenames under data/returns
data:
  returns_dir: "data/returns"
  rf_daily: 0.0

  # Enable any subset of offline sources
  sources: ["news", "social", "fundamentals"]

  offline:
    # Directories for file-backed feeds
    news_dir: "data/news"
    social_dir: "data/social"
    fundamentals_dir: "data/fundamentals"

    # Parsing & selection knobs
    dayfirst: false                 # set true if your files use dd/mm/yyyy
    news_include_poison: "all"      # all | clean_only | poison_only

    # Aggregation weights (contribute to momentum-style score)
    news_weight: 1.0
    social_weight: 1.0

    # Per-episode retrieval limits
    news_limit: 5
    social_limit: 5

# Retrieval & memory (placeholders in the toy runner)
retrieval:
  top_k: 8
  recency_half_life_hours: 48
memory:
  deep_threshold: 0.75
  decay: 0.98

# Debate coordination & judge LLM
coordination:
  type: "debate"                     # debate | manager | contest (future)
  # Fallback criterion if prompts.yaml doesn't provide one
  # You can use {symbol} and {horizon} in this template.
  criterion: "Which argument better predicts {symbol} next-{horizon}-day return? Consider relevance and plausibility."

  judge:
    llm: "hf"                        # none | mock | hf
    model_id: "mistralai/Mistral-7B-Instruct-v0.3"
    max_new_tokens: 96
    temperature: 0.2
    top_p: 0.9
    dtype: "auto"                    # auto | bfloat16 | float16 | float32
    load_8bit: false
    load_4bit: true                  # set true if you want 4-bit quantized loading (bitsandbytes)

# Alpha path and policy thresholds
alpha_path:
  enabled: true
  k: 3                               # (not used in the toy miner yet)

policy:
  buy_thr: 0.10
  sell_thr: -0.10

# Risk gate (toy)
risk:
  stop_loss: 0.08
  take_profit: 0.12

# Attack toggles (not wired in this minimal runner)
attacks:
  A1_social_news: {enabled: false, n_items: 4, stance: 1}
  A2_tools:       {enabled: false}
  A3_debate:      {enabled: false, overlap: 0.6, bull_bias: 0.2}
  A4_policy:      {enabled: false}

# Output
logging:
  out_dir: "runs"
